# -*- coding: utf-8 -*-
"""Copy of Ketan_Individual_ReccSYS_2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBBzOoPso4hPFMKZfMH1xohP1zbhOHi9

From Kodangada Ketan Bopanna

# Objectives

Recommender Systems Course 2024
The dataset contains user-recipe reviews, including ratings and comments. Your goal is to recommend recipes to users based on their past recipe reviews.

Formal requirements include:
* Implement a content-based recommender system.
* Implement a collaborative filtering model.
* Implement a matrix factorization model.
* Document your model development, evaluation and testing in a notebook file. Please use
* comments as well as markdown cells to describe your thought process and intermediate results.
* Include a short conclusion reviewing your approaches and evaluating their performance.

# Loading and data reading
"""

# import matplotlib.pyplot as plt
# import pandas as pd
# from datetime import datetime
# import os
# import numpy as np
# from collections import Counter

# from surprise import Dataset, Reader, KNNBasic, accuracy
# from ieseg_recsys import eval, model
# from sklearn.model_selection import train_test_split
# from scipy import sparse
# from surprise import SVD, CoClustering

# from sklearn.decomposition import TruncatedSVD
# from sklearn.metrics import mean_squared_error
# from sklearn.model_selection import train_test_split
# from surprise import Dataset, Reader, KNNBasic, SVD


# # NLP packages
# import nltk
# from nltk.corpus import stopwords
# from nltk.tokenize import word_tokenize
# from sklearn.feature_extraction.text import TfidfVectorizer
# from nltk.stem.snowball import SnowballStemmer
# from nltk.stem import PorterStemmer

# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import linear_kernel
# from surprise import Dataset, Reader, KNNBasic, accuracy, BaselineOnly, SVD, CoClustering
# from sklearn.metrics.pairwise import cosine_similarity

"""Update:"""

# ============================================
# Auto-install missing packages
# ============================================

import sys
import subprocess
import importlib
def install(package, pip_name=None):
    """
    Install a package if it is not already installed.

    package   : module name used in import
    pip_name  : package name on pip (if different)
    """
    try:
        importlib.import_module(package)
        print(f"✓ {package} already installed")
    except ModuleNotFoundError:
        pip_package = pip_name if pip_name else package
        print(f"Installing {pip_package}...")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-q", pip_package]
        )
        print(f"✓ Installed {pip_package}")

# Packages with different pip names
install("surprise", "scikit-surprise")
install("nltk")
install("sklearn", "scikit-learn")
install("scipy")
install("matplotlib")
install("pandas")
install("numpy")
install("ieseg-recsys")

import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import os
import numpy as np
from collections import Counter

from surprise import Dataset, Reader, KNNBasic, accuracy
from ieseg_recsys import eval, model
from sklearn.model_selection import train_test_split
from scipy import sparse
from surprise import SVD, CoClustering

from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from surprise import Dataset, Reader, KNNBasic, SVD
from surprise import accuracy, BaselineOnly, SVD, CoClustering

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 100)
pd.set_option("display.max_info_columns", 100)

!pip freeze > requirements.txt

"""# Train & Metadata"""

import urllib.request

urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/K10Bops/recommender_Systems/main/data/train_sample.csv",
    "train_sample.csv"
)

urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/K10Bops/recommender_Systems/main/data/metadata_sample.csv",
    "metadata_sample.csv"
)

urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/K10Bops/recommender_Systems/main/data/sample_submission.csv",
    "sample_submission.csv"
)


train = pd.read_csv("train_sample.csv")
metadata = pd.read_csv("metadata_sample.csv")

train.date.describe()

train.info()

metadata.dtypes

# Check unique IDs in both
print(f"Unique IDs in metadata: {metadata['id'].nunique()}")
print(f"Unique IDs in train: {train['recipe_id'].nunique()}")

# Find the intersection
common_ids = set(metadata['id']).intersection(set(train['recipe_id']))
print(f"Actual number of matching IDs: {len(common_ids)}")

metadata['id'] = metadata['id'].astype(str)
train['recipe_id'] = train['recipe_id'].astype(str)

user_recipe = train.merge(
    metadata,
    left_on="recipe_id",
    right_on="id",
    how="inner"
)

print(metadata.info())
print(user_recipe.info())
print(train.info())

metadata.info()

# we will use this later
lookup_recipe_id = user_recipe.drop_duplicates(subset=["recipe_id"], keep="last").set_index("recipe_id")

"""# This is kept aside to be used to lookup the predection IDs"""

lookup_recipe_id.shape

"""# Collaborative Based"""

pd.DataFrame({'Type':user_recipe.dtypes, 'Missing':user_recipe.isna().sum(), "Cnt_unique":user_recipe.nunique()})

user_recipe

user_recipe['merged_id'] = user_recipe['id'].astype(str) +'_' +user_recipe['user_id'].astype(str)

user_recipe

# convert timestamp to datetime
user_recipe["date"] = pd.to_datetime(user_recipe["date"], format="mixed")
user_recipe["submitted"] = pd.to_datetime(user_recipe["submitted"], format="mixed")

user_recipe.name.unique()

print('columns:',user_recipe.columns)
print('shape:', user_recipe.shape)

user_recipe['description'] = user_recipe['description'].fillna('MissingD')

"""## Filtering items with 10+ reviews for collaborative filtering models"""

# filter items with 10+ reviews
review_count = user_recipe["recipe_id"].value_counts()

min_count = 10
recipe_filter = list(review_count[review_count >= min_count].index)

custrecipe_filter = user_recipe[user_recipe['recipe_id'].isin(recipe_filter)].reset_index(drop=True)

print(f"Removed {len(review_count) - (review_count > min_count).sum()} items")

print('user_recipe :',user_recipe.nunique())
print("---------------------------")
print('user_recipe : ',user_recipe.dtypes)
print("---------------------------")
print('custrecipe_filter :',custrecipe_filter.nunique())
print("---------------------------")
print('custrecipe_filter : ',custrecipe_filter.dtypes)

custrecipe_filter = user_recipe.rename(columns={'submitted': 'date_Recipe', 'date': 'date_Reviewed'})



# Assuming custrecipe_filter is a DataFrame and 'name' is the column you want to encode
custrecipe_filter['name_'] = pd.factorize(custrecipe_filter['name'])[0]

custrecipe_filter["date_Recipe"].hist(xrot=20)
plt.title("Distribution of date_Recipe submitted")
plt.show()

# Find median date for
print(custrecipe_filter['date_Reviewed'].median())
#2008-06-13 for User based
# 2008-07-16 for custrecipe_filter
print(custrecipe_filter['date_Recipe'].median())
#2004-04-16 for User based
# 2003-04-03 for custrecipe_filter

custrecipe_filter["date_Reviewed"].hist(xrot=10)
plt.title("Distribution of Review Date")
plt.show()

custrecipe_filter["date_Reviewed"].describe()

custrecipe_filter["date_Recipe"].describe()

np.mean(custrecipe_filter.groupby(['recipe_id']).count()['user_id'])

np.mean(custrecipe_filter.groupby(['user_id']).count()['recipe_id'])

"""## Calories variable"""

## Food types, veg/non veg variable

# 1. Split the column
split_data = custrecipe_filter['nutrition'].str.split(',', expand=True)

# 2. Extract the first column and clean it
# We replace '[' and ']' with nothing (empty string)
custrecipe_filter['calories'] = split_data[0].str.replace(r'[\[\]]', '', regex=True)

# 3. Now convert to numeric
custrecipe_filter['calories'] = pd.to_numeric(custrecipe_filter['calories'], errors='coerce')

# Check the results
print(custrecipe_filter[['nutrition', 'calories']].head())

split_data.info()

custrecipe_filter['food_ty'] = np.nan
custrecipe_filter['food_ty'] = custrecipe_filter['food_ty'].astype('str')

custrecipe_filter['ingredients'].nunique()

import pandas as pd
import numpy as np

def classify_recipe(row):

    ingredients = str(row["ingredients"]).lower()

    calories = row.get("calories", np.nan)
    protein = row.get("protein", np.nan)
    fat = row.get("total_fat", np.nan)
    sugar = row.get("sugar", np.nan)

    # -------------------------
    # Diet
    # -------------------------
    meat = [
        "beef","chicken","pork","ham","bacon","turkey",
        "lamb","sausage","pepperoni","fish","salmon",
        "tuna","shrimp","prawn","crab","lobster"
    ]

    seafood = [
        "fish","salmon","tuna","shrimp","prawn",
        "crab","lobster","cod","trout"
    ]

    if any(x in ingredients for x in seafood):
        diet = "Pescatarian"
    elif any(x in ingredients for x in meat):
        diet = "Non-Vegetarian"
    elif any(x in ingredients for x in ["milk","cheese","butter","egg","eggs","cream","yogurt"]):
        diet = "Vegetarian"
    else:
        diet = "Vegan"

    # -------------------------
    # Course
    # -------------------------
    if any(x in ingredients for x in [
        "cake","cookie","cookies","brownie","ice cream",
        "ice-cream","chocolate","cocoa","pie",
        "muffin","cupcake","pudding"
    ]):
        course = "Dessert"

    elif any(x in ingredients for x in [
        "oats","granola","cereal","toast",
        "pancake","waffle"
    ]):
        course = "Breakfast"

    elif any(x in ingredients for x in [
        "lettuce","spinach","salad","cucumber"
    ]):
        course = "Salad"

    elif any(x in ingredients for x in [
        "broth","stock","soup"
    ]):
        course = "Soup"

    else:
        course = "Main"

    # -------------------------
    # Protein Source
    # -------------------------
    if "chicken" in ingredients:
        protein_source = "Chicken"

    elif any(x in ingredients for x in ["beef","steak"]):
        protein_source = "Beef"

    elif any(x in ingredients for x in ["pork","ham","bacon"]):
        protein_source = "Pork"

    elif any(x in ingredients for x in seafood):
        protein_source = "Seafood"

    elif any(x in ingredients for x in ["egg","eggs"]):
        protein_source = "Egg"

    else:
        protein_source = "Plant"

    # -------------------------
    # Sweet / Savory
    # -------------------------
    if any(x in ingredients for x in [
        "sugar","chocolate","vanilla",
        "cookies","cake","honey"
    ]):
        taste = "Sweet"
    else:
        taste = "Savory"

    # -------------------------
    # Cooking Method
    # -------------------------
    if "bake" in ingredients or "oven" in ingredients:
        cooking = "Baked"

    elif "fry" in ingredients:
        cooking = "Fried"

    elif "grill" in ingredients:
        cooking = "Grilled"

    elif "steam" in ingredients:
        cooking = "Steamed"

    elif "roast" in ingredients:
        cooking = "Roasted"

    else:
        cooking = "Other"

    # -------------------------
    # Health
    # -------------------------
    if pd.notna(calories):

        if calories < 300:
            health = "Low Calorie"

        elif calories < 600:
            health = "Medium Calorie"

        else:
            health = "High Calorie"

    else:
        health = "Unknown"

    return pd.Series({
        "diet": diet,
        "course": course,
        "protein_source": protein_source,
        "taste": taste,
        "cooking_method": cooking,
        "health": health
    })


# Create all columns
custrecipe_filter[
    [
        "diet",
        "course",
        "protein_source",
        "taste",
        "cooking_method",
        "health"
    ]
] = custrecipe_filter.apply(classify_recipe, axis=1)

custrecipe_filter.iloc[:, -7:]

"""## Train & test split

For the collaborative filtering solution, is based on user-item interactions (in this case, user reviews of recipes),
we split the data based on a cutoff date.
The idea behind this approach is to simulate a real-world scenario where the model is trained on historical data (reviews before the cutoff date) and then evaluated on its ability to predict future interactions (reviews after the cutoff date).
"""

cutoff_date = "2009-01-01"

train = custrecipe_filter[custrecipe_filter['date_Reviewed'] < cutoff_date].reset_index(drop=True)
test = custrecipe_filter[custrecipe_filter['date_Reviewed'] >= cutoff_date].reset_index(drop=True)

pd.DataFrame({'Type':train.dtypes, 'Missing':train.isna().sum(), "Cnt_unique":train.nunique()})

# filter columns
filter_cols = ["user_id", "recipe_id", "rating"]

train = train[filter_cols]
test = test[filter_cols]

"""### df_train, df_test"""

# set up reader with min rating and max rating as arguments
reader = Reader(rating_scale=(1, 6))

# surprise training and test set
df_train = Dataset.load_from_df(train, reader).build_full_trainset()
df_test = list(test.itertuples(index=False, name=None))

"""## Fit user-based surprise.KNNBasic using cosine similarity

cosine similarity is a measure of similarity between two non-zero vectors
it is slow for large datasets because it requires comparing each user to every other user
so we have to subset or sample
"""

# set option to cosine similarity and user-based collaborative filtering
options = {'name':'cosine', 'user_based':True}

# select 20 most similar users (min 5)
ub = KNNBasic(k=20, min_k=5, sim_options=options, random_state=42)

# fit on training set
ub.fit(df_train)

pred = ub.test(df_test)
accuracy.rmse(pred)

# percentage impossible predictions
perc_impossible = np.sum([1 for i in pred if i.details["was_impossible"]]) / len(pred)
print(f"Impossible: {perc_impossible:.4f}")

ub.default_prediction()

"""## Fit user-based surprise.KNNBasic using pearson correlation

measures the linear correlation between two variables.
not good at predictions if there’s not enough data on similar users or items.
"""

# set option to cosine similarity and user-based collaborative filtering
options = {'name':'pearson', 'user_based':True}

# select 20 most similar items (min 5)
ib = KNNBasic(k=10, min_k=2, sim_options=options, random_state=42)

# fit on training set
ib.fit(df_train)

pred = ib.test(df_test)
accuracy.rmse(pred)

# percentage impossible predictions
perc_impossible = np.sum([1 for i in pred if i.details["was_impossible"]]) / len(pred)
print(f"Impossible: {perc_impossible:.4f}")

ib.default_prediction()

"""## Fit an ALS

ALS can handle sparse data and is relatively efficient
It works by fixing one factor matrix and solving for the other,
"""

# Select alternating least squares (ALS) and 30 epochs
options = {"method": "als", "n_epochs": 50}
als = BaselineOnly(bsl_options=options)

# fit on training set
als.fit(df_train)

pred = als.test(df_test)
accuracy.rmse(pred)

# percentage impossible predictions
perc_impossible = np.sum([1 for i in pred if i.details["was_impossible"]]) / len(pred)
print(f"Impossible: {perc_impossible:.4f}")

"""Increased the als epoch to 50 from 30 and the RMSE improves by 0.2

## Fit and SVD (surprise.SVD)
"""

# select 20 factors and use probabilistic matrix factorization (no bias)
svd = SVD(n_factors=20, biased=False, random_state=42)

# fit on training set
svd.fit(df_train)

pred = svd.test(df_test)
accuracy.rmse(pred)

# percentage impossible predictions
perc_impossible = np.sum([1 for i in pred if i.details["was_impossible"]]) / len(pred)
print(f"Impossible: {perc_impossible:.4f}")

print(als.default_prediction())
print(svd.default_prediction())

"""## Fit a CoClustering"""

clust = CoClustering(n_cltr_u=10, n_cltr_i=10, n_epochs=50, random_state=42)

clust.fit(df_train)
pred = clust.test(df_test)
accuracy.rmse(pred)

# percentage impossible predictions
perc_impossible = np.sum([1 for i in pred if i.details["was_impossible"]]) / len(pred)
print(f"Impossible: {perc_impossible:.4f}")

"""Impossible =  No issues were face when generated predictions"""

clust.default_prediction()

"""default_prediction is the average rating predicted by the model for all instances when no specific prediction can be made

## Display the top 3 recommendations for a user
"""

train = train.rename(columns={'user': 'user_id', 'item': 'recipe_id'})
train

import random
random.choice(train['user_id'])
#U8016076

robert_rows = train[train['user_id'].str.contains('U8016076', na=False)]
robert_rows



def predict_user_topn(model, train, user, topk=15, item_col='item'):
    """
    Returns topk items for specified user.
    Return type: list

    Args[model, train, user, topk, item_col]
    model:      fitted model (surprise package)
    train:      train set used to fit model
    user:       user id
    topk:       topk items to return
    item_col:   column containing item ids
    """

    # intermediate result dict
    res = {item_col:[], 'pred':[], 'detail':[]}

    # iter through all items contained in train set
    for item in set(train[item_col]) :
        uid, iid, true_r, est, detail = model.predict(user,item)
        # if detail['was_impossible']: continue
        # save to result dict
        res[item_col].append(item)
        res['pred'].append(est)
        res['detail'].append(detail)

    return list(pd.DataFrame(res).sort_values('pred', ascending=False)[:topk][item_col])

# Top 3 recommendations for user "U716504"

user = "U8016076"
topk = 3

res = {}
for model_name, model in dict(user_based=ub, item_based=ib, als=als, svd=svd, coclustering=clust).items():
    pred = predict_user_topn(model, train, user=user, topk=topk, item_col="recipe_id")

    # Get name for each of the predicted recipe IDs
    pred_name = [lookup_recipe_id.loc[i]["name"] for i in pred]

    res[model_name] = pred_name

"""### Reccomendation predict"""

pd.DataFrame(res)

"""1) Loop Through Models: The code iterates through a dictionary containing different recommendation models (user_based, item_based, als, svd, coclustering).
2) Generate Predictions: For each model, to predict the top k recommendations for the specified user (U716504).
3) Lookup Recipe Names: For each predicted recipe ID, it looks up the corresponding recipe name using a DataFrame (lookup_recipe_id).
4) Construct Result Dictionary: The code constructs a dictionary (res)
5) Reccomendations: Finally, the code constructs a Pandas DataFrame from the result dictionary (res) using pd.DataFrame(res),the top recommended recipe names for each model

# Conent Based

## Pre-Processing : Checking Type, missing values and unique counts
"""

pd.DataFrame({'Type':user_recipe.dtypes, 'Missing':user_recipe.isna().sum(), "Cnt_unique":user_recipe.nunique()})

"""Viewing all recipe_id that has notna

## Merged_ID for id and user_id
"""

user_recipe['merged_id'] = user_recipe['id'].astype(str) +'_' +user_recipe['user_id'].astype(str)

"""### custrecipe_filter_sample variable

Rename column to default
"""

custrecipe_filter_sample = user_recipe.sample(n=1500, random_state=127)

custrecipe_filter_sample.minutes.describe()

data = custrecipe_filter_sample[['user_id', 'recipe_id', 'rating', 'tags', 'minutes','steps', 'n_ingredients', 'n_steps']]
data = data.rename(columns={'user_id': 'user', 'recipe_id': 'item'})
data

data.head()

data.user.nunique()

"""## Creating Features"""

data.isna().sum()

"""## 1) prep_time categorizing minutes features"""

# Define the bins for categorizing minutes
bins = [-1, 25, 70, 200, float('inf')]
labels = ['short_prep', 'avg_prep', 'long_prep', 'extremely_long_prep']

# Create a new variable based on the length of minutes
data['prep_time'] = pd.cut(data['minutes'], bins=bins, labels=labels)

# Display the counts of each category
print(data['prep_time'].value_counts())

content_data = data[['prep_time','item']]
# Rename the 'item' column to 'id'
content_data.rename(columns={'item': 'id'}, inplace=True)

"""### One-hot encode the 'prep_time' column"""

# One-hot encode the 'prep_time' column
prep_time_dummies = pd.get_dummies(content_data['prep_time'], prefix='prep_time')
prep_time_dummies = prep_time_dummies.apply(lambda x: x.astype(int))

# Concatenate the one-hot encoded DataFrame with the original DataFrame, keeping the 'data.id' column
content_data = pd.concat([content_data[['id']], prep_time_dummies], axis=1)

content_data

"""## 2) Ingredients Features
## content_data with user
"""

content_data = pd.concat([content_data, custrecipe_filter_sample['ingredients']], axis=1)
content_data

# Convert the ingredients column from string to list if it's not already a list
import ast
if custrecipe_filter_sample['ingredients'].apply(lambda x: isinstance(x, str)).any():
    custrecipe_filter_sample['ingredients'] = custrecipe_filter_sample['ingredients'].apply(ast.literal_eval)

# Explode the ingredients column into separate rows
exploded_df = custrecipe_filter_sample.explode('ingredients')

# Count the frequency of each ingredient per id
ingredient_counts = exploded_df.groupby('id')['ingredients'].value_counts()
ingredient_counts

ingredient_counts

ingredient_counts_df = ingredient_counts.reset_index(name='ing_counts')
ingredient_counts_df

"""### ingredient_counts_df features with id"""

# Find the top 10 most common ingredients
top_ingredients = ingredient_counts_df['ingredients'].value_counts().head(10).index

# Replace all other ingredients with 'other'
ingredient_counts_df['ingredients'] = ingredient_counts_df['ingredients'].apply(lambda x: x if x in top_ingredients else 'other')

# One-hot encode the 'ingredients' column
ingredient_dummies = pd.get_dummies(ingredient_counts_df['ingredients'], prefix='ingredient')

# One-hot encode the 'counts' column
counts_dummies = pd.get_dummies(ingredient_counts_df['ing_counts'], prefix='count')

# Concatenate the one-hot encoded columns with the original DataFrame
ingredient_counts_df = pd.concat([ingredient_counts_df[['id']], ingredient_dummies, counts_dummies], axis=1)

# Convert all columns except 'id' to integers
# Convert all columns except 'id' to integers
for col in ingredient_counts_df.columns[1:]:
    ingredient_counts_df[col] = ingredient_counts_df[col].astype(int)

ingredient_counts_df.head(5)

"""## Merge features content_data"""

# Merge ingredient_counts_df with content_data on the 'id' column
content_data = content_data.merge(ingredient_counts_df, on='id', how='left')

content_data.columns

columns_to_drop = ['ingredients']
content_data = content_data.drop(columns=columns_to_drop)

# Remove 'R' string and convert to int64
# data['item'] = data['item'].str.replace('R', '').astype('int64')
# data['user'] = data['user'].str.replace('U', '').astype('int64')
data

print(data.shape)
print(data.columns)

print(metadata.columns)
print(metadata.dtypes)

"""## 3) feature total_chars_D tag_count_T

### Check for missing values in the description column

total_chars_ofdescription & tag_count_oftags
"""

# Create a explicit copy so you own this new dataframe
metadata_Dis_tag = metadata[['id', 'description', 'tags']].copy()

# Handling missing values using the recommended assignment method
if metadata_Dis_tag['description'].isnull().sum() > 0:
    print("There are missing values in the description column. Handling them...")
    metadata_Dis_tag['description'] = metadata_Dis_tag['description'].fillna('')

# Create features
metadata_Dis_tag['total_chars_D'] = metadata_Dis_tag['description'].apply(len).astype('int64')
metadata_Dis_tag['tag_count_T'] = metadata_Dis_tag['tags'].apply(lambda x: len(x.split(','))).astype('int64')

metadata_Dis_tag.total_chars_D.describe()

# Define the bins for categorizing total_chars_D
bins = [-1, 0, 80, 260, float('inf')]
labels = ['no_descrip', 'short_descrip', 'avg_descrip', 'long_descrip']

# Create a new variable based on the length of total_chars_D
metadata_Dis_tag['description_length'] = pd.cut(metadata_Dis_tag['total_chars_D'], bins=bins, labels=labels)

# Display the counts of each category
print(metadata_Dis_tag['description_length'].value_counts())

# One-hot encode the 'description_length' column
description_length_dummies = pd.get_dummies(metadata_Dis_tag['description_length'], prefix='description_length')
description_length_dummies = description_length_dummies.apply(lambda x: x.astype(int))

# Concatenate the one-hot encoded DataFrame with the original DataFrame, keeping the 'id' column
metadata_Dis_tag = pd.concat([metadata_Dis_tag[['id']], description_length_dummies], axis=1)
metadata_Dis_tag

"""### Merge metadata_Dis_tag with content_data on the 'id' column"""

content_data = content_data.merge(metadata_Dis_tag, on='id', how='left')
content_data

"""## 4) Features Tags one hot encoding"""

from sklearn.preprocessing import MultiLabelBinarizer

# Faster, vectorized approach
mlb = MultiLabelBinarizer()
tags_encoded = pd.DataFrame(mlb.fit_transform(data['tags']), columns=mlb.classes_, index=data.index)

# Join all columns at once (avoiding the fragmentation warning)
data_with_tags = pd.concat([data[['item']], tags_encoded], axis=1)

# # Step 1: Split the comma-separated values in the 'tags' column
# data.loc[:, 'tags'] = data['tags'].apply(lambda x: [tag.strip().strip("'\"") for tag in x.strip('[]').split(',')] if isinstance(x, str) else [])

# # Step 2: Extract unique tags
# unique_tags = set(tag for tags_list in data['tags'] for tag in tags_list)

# # Step 3: Create new binary columns for each unique tag and assign values
# for tag in unique_tags:
#     data.loc[:, tag] = data['tags'].apply(lambda x: 1 if tag in x else 0)

# # Create a copy of the DataFrame with the additional columns
# data_with_tags = data[['item'] + list(unique_tags)]
# data_with_tags

content_data = content_data.merge(data_with_tags, left_on='id',right_on='item', how='left')

content_data

content_data.columns

"""## Drop Columns"""

# columns_to_drop = ['item', 'rating', 'tags', 'minutes', 'steps','n_ingredients','n_steps' ]
# data = data.drop(columns=columns_to_drop)

data.shape

content_data = content_data.groupby('id').last()
content_data

content_data

"""## Change to INT"""

# Convert columns to integer type
data_index = content_data.copy()
columns_to_drop = ['item']
data_index = data_index.drop(columns=columns_to_drop)
data_index

data_index = data_index.astype({col: int for col in data_index.columns if col != 'index'})

data_index

"""## Train & Test Conent based"""

data_index.head()

print(train.shape)

custrecipe_filter_sample

columns = ['user_id', 'recipe_id', 'rating']
train = custrecipe_filter_sample[columns]
print(train.head())

train = train.rename(columns={'user_id': 'user', 'recipe_id': 'item'})
train.head()

# train-test split
train, test = train_test_split(train, test_size=0.3, random_state=127)

# reset index
train = train.reset_index(drop=True)
test = test.reset_index(drop=True)

print(data_index.shape)
print(train.shape)
print(test.shape)

reader = Reader(rating_scale=(1, 6))
df_train = Dataset.load_from_df(train, reader).build_full_trainset()
df_test = list(test.itertuples(index=False, name=None))

"""# Results"""

# Model dictionary
model_dict = {
    'user_based_cosine': ub,
    'als': als,
    'svd': svd,
    'coclustering': clust
}

overview = pd.concat([eval.evaluate(mod.fit(df_train).test(df_test), topn=5, rating_cutoff=4) for mod in model_dict.values()], axis=1)
overview.columns = list(model_dict.keys())
overview

"""ALS and user-based cosine similarity models perform similarly and have the lowest RMSE values, indicating better accuracy."""

df_train

"""I keep getting this erro AttributeError: 'CoClustering' object has no attribute 'ContentBased'
And only way is to load the packages again
"""

# !pip install --upgrade ieseg_recsys.model.ContentBased.

# And only way is to load the packages again
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import os
import numpy as np
from collections import Counter

from surprise import Dataset, Reader, KNNBasic, accuracy
from ieseg_recsys import eval, model
from sklearn.model_selection import train_test_split
from scipy import sparse
from surprise import SVD, CoClustering

from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from surprise import Dataset, Reader, KNNBasic, SVD

"""## fit and predict"""

# init content-based
cb = model.ContentBased(NN=10)

# fit on content
cb.fit(data_index)

# fit on train_ratings
cb.fit_ratings(df_train)

# predict test ratings
cb_pred = cb.test(df_test)

#AttributeError: 'DataFrame' object has no attribute 'append'

# compute metrics
cb_res = eval.evaluate(cb_pred, topn=5, rating_cutoff=4).rename(columns={'value':'Content_based_10'})
cb_res

overview = pd.concat([overview, cb_res], axis=1)
overview

"""The lowest RMSE is the Alternating Least Squares (ALS) model, with an RMSE of approximately 1.075162.
Therefore, based on the RMSE metric alone, the ALS model performs the best

# Exporting the files
"""

# id -> user_id, recipe_id
submission = pd.read_csv("sample_submission.csv")
submission[["user_id", "recipe_id"]] = submission["id"].str.split("_", expand=True)
submission = submission.drop('rating', axis=1)
submission

def get_rating(model, user, item):
    _, _, _, est, _ = model.predict(user, item)
    return est

# Model dictionary
model_dict = {
    'user_based': ub,
    'item_based': ib,
    'als': als,
    #'als_with_H-P Tuning & C-V': als_best_algo,
    'svd': svd,
    #'svd_with_H-P Tuning & C-V': svd_best_algo,
    'coclustering': clust
}

# Iterate through each model
for model_name, model in model_dict.items():
    # Apply the model to get ratings
    submission[model_name + '_rating'] = submission.apply(lambda row: get_rating(model, row['user_id'], row['recipe_id']), axis=1)

    # Create the 'id' column by combining 'user_id' and 'recipe_id'
    submission['id'] = submission['user_id'] + '_' + submission['recipe_id']

    # Create a new DataFrame with the 'id' and model-specific rating column, then rename the rating column
    output_df = submission[['id', model_name + '_rating']].rename(columns={model_name + '_rating': 'rating'})

    # Save to CSV, using the model name to label each file
    output_file_name = model_name + '.csv'
    output_df.to_csv(output_file_name, index=False)
    print(f"Saved {output_file_name}")